<?php

// The array $books is a "snapshot" of what this document produces. Since random
// values are used here, the output differs a bit each time the file is loaded.  


// Fake book titles and authors, generated by chatGPT: 
$books = [
  ["title" => "The Enigmatic Chronicles", "author" => "John Doe"],
  ["title" => "Secrets of the Lost Galaxy", "author" => "Jane Smith"],
  ["title" => "Whispers in the Shadows", "author" => "Alice Johnson"],
  ["title" => "The Phantom's Curse", "author" => "Robert Davis"],
  ["title" => "Dreams of the Forgotten Kingdom", "author" => "Emily White"],
  ["title" => "The Starship Voyager", "author" => "Michael Brown"],
  ["title" => "Forgotten Realms: Quest for the Orb", "author" => "Sarah Green"],
  ["title" => "Echoes of the Timeless Mage", "author" => "Daniel Lee"],
  ["title" => "The Elysian Prophecy", "author" => "Linda Harris"],
  ["title" => "The Crystal Key", "author" => "William Turner"],
  ["title" => "A Song of Echoing Dreams", "author" => "Susan Clark"],
  ["title" => "The Alabaster Enchantment", "author" => "James Wilson"],
  ["title" => "Cogs of the Clockwork Kingdom", "author" => "Karen Hall"],
  ["title" => "Legends of the Celestial Guardians", "author" => "Brian Adams"],
  ["title" => "The Emberheart Chronicles", "author" => "Elizabeth Martinez"],
  ["title" => "Whispers from the Abyss", "author" => "Thomas Mitchell"],
  ["title" => "Tales of the Ethereal Realm", "author" => "Patricia Turner"],
  ["title" => "The Midnight Carnival", "author" => "Robert Davis"],
  ["title" => "The Clockwork Conspiracy", "author" => "Maria Garcia"],
  ["title" => "Serpents of the Emerald Isle", "author" => "Michael Brown"],
  ["title" => "The Enchanted Labyrinth", "author" => "Catherine Johnson"],
  ["title" => "The Shadowed Prophecies", "author" => "John Doe"],
  ["title" => "Chronicles of the Celestial Isles", "author" => "Jane Smith"],
  ["title" => "The Gilded Sphinx", "author" => "Linda Harris"],
  ["title" => "Echoes of the Ancient Runes", "author" => "John Doe"],
  ["title" => "The Astral Wonders", "author" => "Susan Clark"],
  ["title" => "Songs of the Eternal Realm", "author" => "Brian Adams"],
  ["title" => "Whispers of the Starlit Forest", "author" => "Maria Garcia"],
  ["title" => "The Sapphire Sorcerer", "author" => "Patricia Turner"],
  ["title" => "Secrets of the Silver Veil", "author" => "James Wilson"],
  ["title" => "The Obsidian Codex", "author" => "Elizabeth Martinez"],
  ["title" => "Echoes from the Abyss", "author" => "Thomas Mitchell"],
  ["title" => "Whispers of the Frozen Wastes", "author" => "Robert Davis"],
  ["title" => "The Lost Kingdom of Eldoria", "author" => "Emily White"],
  ["title" => "Chronicles of the Crystal Serpent", "author" => "Linda Harris"],
  ["title" => "The Enchanted Masquerade", "author" => "Daniel Lee"],
  ["title" => "The Arcane Almanac", "author" => "Maria Garcia"],
  ["title" => "Echoes of the Starforged Empire", "author" => "Susan Clark"],
  ["title" => "The Enigmatic Apparition", "author" => "Patricia Turner"],
  ["title" => "The Cursed Amulet", "author" => "James Wilson"],
  ["title" => "Secrets of the Whispering Woods", "author" => "Brian Adams"],
  ["title" => "The Midnight Spellbook", "author" => "John Doe"],
  ["title" => "Dreams of the Celestial Voyager", "author" => "Alice Johnson"],
  ["title" => "The Enchanted Paradox", "author" => "Robert Davis"],
  ["title" => "The Labyrinth of Enigma", "author" => "Hiroshi Tanaka"],
  ["title" => "Whispers from the Silk Road", "author" => "Li Wei"],
  ["title" => "The Bamboo Forest Mystery", "author" => "Aleksandr Ivanov"],
  ["title" => "Legends of the Golden Phoenix", "author" => "Yuki Nakamura"],
  ["title" => "The Enchanted Jade Garden", "author" => "Chen Wei"],
  ["title" => "Echoes from the Red Pagoda", "author" => "Sofia Martinez"],
];

$genres = [
  "Fantasy",
  "Science Fiction",
  "Mystery",
  "Romance",
  "Thriller",
  "Historical Fiction",
  "Horror",
  "Adventure",
  "Dystopian",
  "Non-Fiction",
];

$colors = [
  "Red",
  "Blue",
  "Green",
  "Yellow",
  "Purple",
  "Orange",
  "Pink",
  "Teal",
  "Brown",
  "Gray",
];

// populate $books with more data
foreach ($books as $key => $book) {
  $books[$key]["test"] = "test";
  $books[$key]["id"] = $key;
  $books[$key]["genre"] = $genres[rand(0, 9)];
  $books[$key]["color"] = $colors[rand(0, 9)];
}

echo "<pre>";
print_r($books);
