<?php

// array $books generated in "./data.source.php".

$books = array(
  0 =>
  array(
    'title' => 'Eldoria Secrets',
    'author' => 'John Smith',
    'id' => 0,
    'genre' => 'Fantasy',
    'year' => 2014,
    'pages' => 358,
    'color' => 'var(--book-purple)',
    'fonts' => 'Roboto Slab',
  ),
  1 =>
  array(
    'title' => 'City Secrets',
    'author' => 'Daniel Chen',
    'id' => 1,
    'genre' => 'Historical Fiction',
    'year' => 1846,
    'pages' => 381,
    'color' => 'var(--book-red)',
    'fonts' => 'Lora',
  ),
  2 =>
  array(
    'title' => 'Remember the Journey',
    'author' => 'Lisa Kim',
    'id' => 2,
    'genre' => 'Mystery',
    'year' => 1861,
    'pages' => 332,
    'color' => 'var(--book-yellow)',
    'fonts' => 'Chivo Mono',
  ),
  3 =>
  array(
    'title' => 'Lost Legends',
    'author' => 'Emily Davis',
    'id' => 3,
    'genre' => 'Non-Fiction',
    'year' => 1927,
    'pages' => 304,
    'color' => 'var(--book-yellow)',
    'fonts' => 'Sono',
  ),
  4 =>
  array(
    'title' => 'Hidden Mysteries',
    'author' => 'Emily Davis',
    'id' => 4,
    'genre' => 'Thriller',
    'year' => 1929,
    'pages' => 393,
    'color' => 'var(--book-blue)',
    'fonts' => 'Chivo Mono',
  ),
  5 =>
  array(
    'title' => 'Search Atlantis',
    'author' => 'Ahmed El-Masri',
    'id' => 5,
    'genre' => 'Dystopian',
    'year' => 1876,
    'pages' => 226,
    'color' => 'var(--book-red)',
    'fonts' => 'Lora',
  ),
  6 =>
  array(
    'title' => 'World of Wonders',
    'author' => 'Nadia Aziz',
    'id' => 6,
    'genre' => 'Thriller',
    'year' => 1914,
    'pages' => 238,
    'color' => 'var(--book-red)',
    'fonts' => 'Chivo Mono',
  ),
  7 =>
  array(
    'title' => 'Mystical Island',
    'author' => 'Susan White',
    'id' => 7,
    'genre' => 'Fantasy',
    'year' => 1878,
    'pages' => 285,
    'color' => 'var(--book-yellow)',
    'fonts' => 'Roboto Slab',
  ),
  8 =>
  array(
    'title' => 'Great Wall Chronicles',
    'author' => 'Yuki Nakamura',
    'id' => 8,
    'genre' => 'Non-Fiction',
    'year' => 1976,
    'pages' => 242,
    'color' => 'var(--book-purple)',
    'fonts' => 'Roboto Slab',
  ),
  9 =>
  array(
    'title' => 'Mysterious Island',
    'author' => 'Susan White',
    'id' => 9,
    'genre' => 'Thriller',
    'year' => 1813,
    'pages' => 342,
    'color' => 'var(--book-yellow)',
    'fonts' => 'Chivo Mono',
  ),
  10 =>
  array(
    'title' => 'Exploring Silk Road',
    'author' => 'Li Wei',
    'id' => 10,
    'genre' => 'Romance',
    'year' => 1875,
    'pages' => 386,
    'color' => 'var(--book-purple)',
    'fonts' => 'Chivo Mono',
  ),
  11 =>
  array(
    'title' => 'Ancient Myths',
    'author' => 'John Smith',
    'id' => 11,
    'genre' => 'Science Fiction',
    'year' => 1869,
    'pages' => 351,
    'color' => 'var(--book-purple)',
    'fonts' => 'Chivo Mono',
  ),
  12 =>
  array(
    'title' => 'Treasure Hunt',
    'author' => 'Sophia Garcia',
    'id' => 12,
    'genre' => 'Horror',
    'year' => 2000,
    'pages' => 327,
    'color' => 'var(--book-orange)',
    'fonts' => 'Chivo Mono',
  ),
  13 =>
  array(
    'title' => 'Enchanted Tales',
    'author' => 'Mary Brown',
    'id' => 13,
    'genre' => 'Historical Fiction',
    'year' => 1943,
    'pages' => 380,
    'color' => 'var(--book-yellow)',
    'fonts' => 'Roboto Slab',
  ),
  14 =>
  array(
    'title' => 'Alchemist\'s Legacy',
    'author' => 'Karen Adams',
    'id' => 14,
    'genre' => 'Fantasy',
    'year' => 1929,
    'pages' => 221,
    'color' => 'var(--book-green)',
    'fonts' => 'Sono',
  ),
  15 =>
  array(
    'title' => 'Great Wall Odyssey',
    'author' => 'Mei Ling',
    'id' => 15,
    'genre' => 'Science Fiction',
    'year' => 2008,
    'pages' => 237,
    'color' => 'var(--book-red)',
    'fonts' => 'Chivo Mono',
  ),
  16 =>
  array(
    'title' => 'Lost in Time',
    'author' => 'Robert Lee',
    'id' => 16,
    'genre' => 'Fantasy',
    'year' => 1921,
    'pages' => 360,
    'color' => 'var(--book-yellow)',
    'fonts' => 'Oswald',
  ),
  17 =>
  array(
    'title' => 'Timeless Secrets',
    'author' => 'Robert Lee',
    'id' => 17,
    'genre' => 'Non-Fiction',
    'year' => 1982,
    'pages' => 235,
    'color' => 'var(--book-blue)',
    'fonts' => 'Chivo Mono',
  ),
  18 =>
  array(
    'title' => 'Lost Treasure Hunt',
    'author' => 'Sophia Garcia',
    'id' => 18,
    'genre' => 'Adventure',
    'year' => 1888,
    'pages' => 324,
    'color' => 'var(--book-orange)',
    'fonts' => 'Sono',
  ),
  19 =>
  array(
    'title' => 'Tales from Orient',
    'author' => 'Luis Rodriguez',
    'id' => 19,
    'genre' => 'Romance',
    'year' => 2015,
    'pages' => 278,
    'color' => 'var(--book-green)',
    'fonts' => 'Lora',
  ),
  20 =>
  array(
    'title' => 'Silk Road Adventures',
    'author' => 'Tenzin Wang',
    'id' => 20,
    'genre' => 'Romance',
    'year' => 1857,
    'pages' => 300,
    'color' => 'var(--book-orange)',
    'fonts' => 'Oswald',
  ),
  21 =>
  array(
    'title' => 'Great Wall Chronicles',
    'author' => 'Yuki Nakamura',
    'id' => 21,
    'genre' => 'Thriller',
    'year' => 1992,
    'pages' => 345,
    'color' => 'var(--book-red)',
    'fonts' => 'Roboto Slab',
  ),
  22 =>
  array(
    'title' => 'Worldly Wonders',
    'author' => 'Nadia Aziz',
    'id' => 22,
    'genre' => 'Horror',
    'year' => 1924,
    'pages' => 244,
    'color' => 'var(--book-purple)',
    'fonts' => 'Oswald',
  ),
  23 =>
  array(
    'title' => 'Journey\'s End',
    'author' => 'David Johnson',
    'id' => 23,
    'genre' => 'Non-Fiction',
    'year' => 1941,
    'pages' => 358,
    'color' => 'var(--book-purple)',
    'fonts' => 'Sono',
  ),
  24 =>
  array(
    'title' => 'Sphinx Secrets',
    'author' => 'Michael Hall',
    'id' => 24,
    'genre' => 'Fantasy',
    'year' => 1893,
    'pages' => 348,
    'color' => 'var(--book-orange)',
    'fonts' => 'Oswald',
  ),
  25 =>
  array(
    'title' => 'Hidden Treasures',
    'author' => 'Susan White',
    'id' => 25,
    'genre' => 'Romance',
    'year' => 1916,
    'pages' => 205,
    'color' => 'var(--book-blue)',
    'fonts' => 'Sono',
  ),
  26 =>
  array(
    'title' => 'Legacy of Alchemy',
    'author' => 'Karen Adams',
    'id' => 26,
    'genre' => 'Fantasy',
    'year' => 1907,
    'pages' => 393,
    'color' => 'var(--book-red)',
    'fonts' => 'Chivo Mono',
  ),
  27 =>
  array(
    'title' => 'Oriental Adventures',
    'author' => 'Luis Rodriguez',
    'id' => 27,
    'genre' => 'Mystery',
    'year' => 1806,
    'pages' => 204,
    'color' => 'var(--book-red)',
    'fonts' => 'Roboto Slab',
  ),
  28 =>
  array(
    'title' => 'Wall Expeditions',
    'author' => 'Mei Ling',
    'id' => 28,
    'genre' => 'Horror',
    'year' => 1827,
    'pages' => 311,
    'color' => 'var(--book-yellow)',
    'fonts' => 'Sono',
  ),
  29 =>
  array(
    'title' => 'Eldoria Chronicles',
    'author' => 'John Smith',
    'id' => 29,
    'genre' => 'Fantasy',
    'year' => 1924,
    'pages' => 251,
    'color' => 'var(--book-green)',
    'fonts' => 'Oswald',
  ),
  30 =>
  array(
    'title' => 'Journey to Remember',
    'author' => 'Lisa Kim',
    'id' => 30,
    'genre' => 'Horror',
    'year' => 1899,
    'pages' => 269,
    'color' => 'var(--book-yellow)',
    'fonts' => 'Roboto Slab',
  ),
  31 =>
  array(
    'title' => 'Enchanted Forest',
    'author' => 'Mary Brown',
    'id' => 31,
    'genre' => 'Mystery',
    'year' => 1821,
    'pages' => 366,
    'color' => 'var(--book-orange)',
    'fonts' => 'Chivo Mono',
  ),
  32 =>
  array(
    'title' => 'Enchanted Tales',
    'author' => 'Mary Brown',
    'id' => 32,
    'genre' => 'Mystery',
    'year' => 1966,
    'pages' => 377,
    'color' => 'var(--book-green)',
    'fonts' => 'Sono',
  ),
  33 =>
  array(
    'title' => 'Mysteries Unveiled',
    'author' => 'Emily Davis',
    'id' => 33,
    'genre' => 'Historical Fiction',
    'year' => 1814,
    'pages' => 354,
    'color' => 'var(--book-green)',
    'fonts' => 'Roboto Slab',
  ),
  34 =>
  array(
    'title' => 'Journey Chronicles',
    'author' => 'David Johnson',
    'id' => 34,
    'genre' => 'Dystopian',
    'year' => 1911,
    'pages' => 296,
    'color' => 'var(--book-blue)',
    'fonts' => 'Sono',
  ),
  35 =>
  array(
    'title' => 'Eastern Mysteries',
    'author' => 'Kenji Sato',
    'id' => 35,
    'genre' => 'Adventure',
    'year' => 1827,
    'pages' => 245,
    'color' => 'var(--book-yellow)',
    'fonts' => 'Chivo Mono',
  ),
  36 =>
  array(
    'title' => 'Forbidden City',
    'author' => 'Daniel Chen',
    'id' => 36,
    'genre' => 'Science Fiction',
    'year' => 1972,
    'pages' => 235,
    'color' => 'var(--book-purple)',
    'fonts' => 'Lora',
  ),
  37 =>
  array(
    'title' => 'Atlantis Quest',
    'author' => 'Ahmed El-Masri',
    'id' => 37,
    'genre' => 'Thriller',
    'year' => 1918,
    'pages' => 297,
    'color' => 'var(--book-blue)',
    'fonts' => 'Roboto Slab',
  ),
  38 =>
  array(
    'title' => 'Secrets of Sphinx',
    'author' => 'Michael Hall',
    'id' => 38,
    'genre' => 'Science Fiction',
    'year' => 1869,
    'pages' => 375,
    'color' => 'var(--book-purple)',
    'fonts' => 'Roboto Slab',
  ),
  39 =>
  array(
    'title' => 'Silk Road Explorer',
    'author' => 'Li Wei',
    'id' => 39,
    'genre' => 'Mystery',
    'year' => 1856,
    'pages' => 383,
    'color' => 'var(--book-purple)',
    'fonts' => 'Oswald',
  ),
  40 =>
  array(
    'title' => 'Journey to Unknown',
    'author' => 'David Johnson',
    'id' => 40,
    'genre' => 'Horror',
    'year' => 1856,
    'pages' => 335,
    'color' => 'var(--book-yellow)',
    'fonts' => 'Roboto Slab',
  ),
  41 =>
  array(
    'title' => 'Mysteries of East',
    'author' => 'Kenji Sato',
    'id' => 41,
    'genre' => 'Romance',
    'year' => 2015,
    'pages' => 330,
    'color' => 'var(--book-red)',
    'fonts' => 'Chivo Mono',
  ),
  42 =>
  array(
    'title' => 'Lost Treasures',
    'author' => 'Robert Lee',
    'id' => 42,
    'genre' => 'Horror',
    'year' => 1846,
    'pages' => 292,
    'color' => 'var(--book-red)',
    'fonts' => 'Sono',
  ),
  43 =>
  array(
    'title' => 'Silk Road Wonders',
    'author' => 'Tenzin Wang',
    'id' => 43,
    'genre' => 'Science Fiction',
    'year' => 1932,
    'pages' => 379,
    'color' => 'var(--book-green)',
    'fonts' => 'Sono',
  ),
);
