<?php

// The array $books in "./data-generated.php" is a "snapshot" of what this document outputs. 
// Since random values are used here, the output differs a bit each time the file is loaded.
// Therefore a "static" version was exported out and used further on.  


// Fake book titles and authors, generated by chatGPT 3.5: 
$books = [
  ["title" => "Eldoria Secrets", "author" => "John Smith"],
  ["title" => "Mysteries Unveiled", "author" => "Emily Davis"],
  ["title" => "Journey to Unknown", "author" => "David Johnson"],
  ["title" => "Enchanted Forest", "author" => "Mary Brown"],
  ["title" => "Lost in Time", "author" => "Robert Lee"],
  ["title" => "Mysterious Island", "author" => "Susan White"],
  ["title" => "Secrets of Sphinx", "author" => "Michael Hall"],
  ["title" => "Alchemist's Legacy", "author" => "Karen Adams"],
  ["title" => "Forbidden City", "author" => "Daniel Chen"],
  ["title" => "Journey to Remember", "author" => "Lisa Kim"],
  ["title" => "Tales from Orient", "author" => "Luis Rodriguez"],
  ["title" => "Lost Treasure Hunt", "author" => "Sophia Garcia"],
  ["title" => "Search Atlantis", "author" => "Ahmed El-Masri"],
  ["title" => "Great Wall Odyssey", "author" => "Mei Ling"],
  ["title" => "Silk Road Adventures", "author" => "Tenzin Wang"],
  ["title" => "World of Wonders", "author" => "Nadia Aziz"],
  ["title" => "Mysteries of East", "author" => "Kenji Sato"],
  ["title" => "Silk Road Explorer", "author" => "Li Wei"],
  ["title" => "Great Wall Chronicles", "author" => "Yuki Nakamura"],
  ["title" => "Eldoria Chronicles", "author" => "John Smith"],
  ["title" => "Hidden Mysteries", "author" => "Emily Davis"],
  ["title" => "Journey Chronicles", "author" => "David Johnson"],
  ["title" => "Enchanted Tales", "author" => "Mary Brown"],
  ["title" => "Lost Treasures", "author" => "Robert Lee"],
  ["title" => "Mystical Island", "author" => "Susan White"],
  ["title" => "Sphinx Secrets", "author" => "Michael Hall"],
  ["title" => "Legacy of Alchemy", "author" => "Karen Adams"],
  ["title" => "City Secrets", "author" => "Daniel Chen"],
  ["title" => "Remember the Journey", "author" => "Lisa Kim"],
  ["title" => "Oriental Adventures", "author" => "Luis Rodriguez"],
  ["title" => "Treasure Hunt", "author" => "Sophia Garcia"],
  ["title" => "Atlantis Quest", "author" => "Ahmed El-Masri"],
  ["title" => "Wall Expeditions", "author" => "Mei Ling"],
  ["title" => "Silk Road Wonders", "author" => "Tenzin Wang"],
  ["title" => "Worldly Wonders", "author" => "Nadia Aziz"],
  ["title" => "Eastern Mysteries", "author" => "Kenji Sato"],
  ["title" => "Exploring Silk Road", "author" => "Li Wei"],
  ["title" => "Great Wall Chronicles", "author" => "Yuki Nakamura"],
  ["title" => "Ancient Myths", "author" => "John Smith"],
  ["title" => "Lost Legends", "author" => "Emily Davis"],
  ["title" => "Journey's End", "author" => "David Johnson"],
  ["title" => "Enchanted Tales", "author" => "Mary Brown"],
  ["title" => "Timeless Secrets", "author" => "Robert Lee"],
  ["title" => "Hidden Treasures", "author" => "Susan White"],
];

shuffle($books);

$genres = [
  "Fantasy",
  "Science Fiction",
  "Mystery",
  "Romance",
  "Thriller",
  "Historical Fiction",
  "Horror",
  "Adventure",
  "Dystopian",
  "Non-Fiction",
];

$colors = [
  "var(--book-yellow)",
  "var(--book-orange)",
  "var(--book-red)",
  "var(--book-purple)",
  "var(--book-blue)",
  "var(--book-green)",
];

$fonts = [
  "Sono",
  "Chivo Mono",
  "Lora",
  "Roboto Slab",
  "Oswald",
];

// populate $books with more data
foreach ($books as $key => $book) {
  $books[$key]["id"] = $key;
  $books[$key]["genre"] = $genres[rand(0, 9)];
  $books[$key]["year"] = rand(1800, 2023);
  $books[$key]["pages"] = rand(200, 400);
  $books[$key]["color"] = $colors[rand(0, 5)];
  $books[$key]["fonts"] = $fonts[rand(0, 4)];
}

// echo "<pre>";
// var_export($books);
